### ISSUE TITLE
SQLITE_CANTOPEN: unable to open database file

### ISSUE THREAD

**Issue by CoZmoTheGod** [Ethorbit/Discord_Sticky-Message-Bot#13]
Fresh install using Pterodactyl and maybe I'm not specifying where the db file is but it won't open the db file.
![image](https://github.com/Ethorbit/Discord_Sticky-Message-Bot/assets/37917612/eb69bc90-e51b-45e7-92fc-e981cb93d491)
![image](https://github.com/Ethorbit/Discord_Sticky-Message-Bot/assets/37917612/d0405032-f71b-4311-92e9-4af20fc555a3)

**Comment by Ethorbit** [comment]
> Fresh install using Pterodactyl and maybe I'm not specifying where the db file is but it won't open the db file. ![image](https://user-images.githubusercontent.com/37917612/264918227-eb69bc90-e51b-45e7-92fc-e981cb93d491.png) ![image](https://user-images.githubusercontent.com/37917612/264918254-d0405032-f71b-4311-92e9-4af20fc555a3.png)

It should be /home/container/bot.db in this case, the path should begin with a slash

**Comment by Ethorbit** [comment]
Closing since this doesn't appear to be an issue with the bot
