### ISSUE TITLE
!sticky removeall <channel id> is not removing the sticky message

### ISSUE THREAD

**Issue by aCosmicGlitch** [Ethorbit/Discord_Sticky-Message-Bot#2]
I'm getting this error message when i try to remove the sticky message: Error deleting stickies. There were no stickies in that channel.

also its not showing the correct sticky lists.

**Comment by Ethorbit** [comment]
> I'm getting this error message when i try to remove the sticky message: Error deleting stickies. There were no stickies in that channel.
> 
> also its not showing the correct sticky lists.

Did you try `!sticky list` ? That should show all stickies for each channel.

If it does list things, send an image of it with the exact commands you're typing for removeall

**Comment by aCosmicGlitch** [comment]
I'm using the same list command. It does not list all the stickies and it does not sometimes removes the stickies from the channel. 

I'm using `!sticky removeall <channel id> ` command
