### ISSUE TITLE
Send a sticky message after messages from other bots

### ISSUE THREAD

**Issue by Complex1t** [Ethorbit/Discord_Sticky-Message-Bot#9]
Is there a way for the bot to send a sticky message after another bot's message? I am using the sticky message bot in a bot commands channel to remind users of available commands, but the sticky message bot does not recognize other bot's messages, and thus it is not the last message sent.

**Comment by Ethorbit** [comment]
> Is there a way for the bot to send a sticky message after another bot's message? I am using the sticky message bot in a bot commands channel to remind users of available commands, but the sticky message bot does not recognize other bot's messages, and thus it is not the last message sent.

Yes, this should be easy.
In [src/bot.js line 74](https://github.com/Ethorbit/Discord_Sticky-Message-Bot/blob/main/src/bot.js#L74), it says:
```js
    if (msg.author.bot)
        return;
```
which means it just ignores messages created by any bot.

replacing it with this:
```js
    if (msg.author.bot && msg.author.id == global.discordApplication.id)
        return;
```
should make it only ignore itself

Let me know if this works without any issues, and I'll implement the change.

**Comment by Complex1t** [comment]
That worked, thanks! I should also note that I had to add a little delay to sending sticky messages as sometimes the sticky message would be sent before bot messages.
